language: node_js
os:
  - linux
  - osx
dist: bionic
osx_image: xcode12
node_js:
  - "10"
  - "12"
  - "13"
  - lts/*
  - node
install: npm ci
script:
  - go version
  - npm link
  - npm run build
  - npm test
