language: node_js
node_js:
  - "10"
  - "12"
  - "13"
  - lts/*
  - node
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12
install: npm ci
script:
  - npm link
  - npm run build
  - npm test
