skip_commits:
  files:
    - LICENSE
    - CONTRIBUTING.md
    - README.md
    - .travis.yml
environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"
install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version
  - npm ci
build_script:
  - npm link
  - npm run build
test_script:
  - npm test
